language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5

notifications:
  email: false

services:
  - redis

script: go test -v

install:
  - go get -u gopkg.in/redis.v3
  - go get -u github.com/matttproud/gocheck
